name: Build Docker Image

on:
  push:
    branches:
      - feature/improve-readme

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ai-system-analysis-tool .

      - name: Run container
        run: docker run ai-system-analysis-tool

      - name: Run container and validate output
        run: |
          output=$(docker run ai-system-analysis-tool)
          echo "$output"

          echo "$output" | grep "Log Analysis Result" || exit 1
          echo "$output" | grep "System Summary" || exit 1
          echo "$output" | grep "Anomaly Detection" || exit 1
